name: CD

on:
  push:
    branches: [main] # Only runs on main branch pushes

jobs:
  deploy-to-render:
    runs-on: ubuntu-latest
    environment:
      name: Render-Prod # Make sure this matches your GitHub Environment name

    steps:
      - name: Trigger Render Deploy
        env:
          RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL_STATIC_SITE }}
        run: |
          if [ -z "$RENDER_DEPLOY_HOOK_URL" ]; then
            echo "Render deploy hook URL secret is not set. Skipping deployment."
            exit 1
          fi
          echo "Triggering Render deployment..."
          curl --fail -X POST "$RENDER_DEPLOY_HOOK_URL"
          echo "Render deployment triggered."
